name: LootMonsters
version: @version@
main: me.jishuna.lootmonsters.LootMonsters
authors: [Jishuna]
api-version: 1.17

commands:
  lootmonsters:
    description: 'Base plugin command'
    aliases: [lootm]
permissions:
  lootmonsters.command:
    default: true
  lootmonsters.command.info:
    default: true
  lootmonsters.command.reload:
    default: op
    
